name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.1'
      project_option:
        type: choice
        description: project to publish
        options:
          - nx-generators
          - heroicons
          - tabler-icons
          - flowbite-icons
          - flag-icons
          - lucide-icons
          - circle-flags
          - bootstrap-icons
          - lineicons
  push:
    tags:
      - v*.*.*

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build project
        run: npx nx build ${{ github.event.inputs.project_option }}
        shell: bash

      - name: Version
        run: npx nx release version ${{ github.event.inputs.version }} --projects=${{ github.event.inputs.project_option }}
        shell: bash

      - name: Publish packages
        run: npx nx release publish --projects=${{ github.event.inputs.project_option }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
